[package]
name = "omdrop-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "omdropctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
omdrop-core = { path = "../omdrop-core" }
omdrop-platform-linux = { path = "../omdrop-platform-linux" }
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
