[package]
name = "omdrop-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "omdropd"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
omdrop-core = { path = "../omdrop-core" }
omdrop-platform-linux = { path = "../omdrop-platform-linux" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
