[package]
name = "omdrop-radio-helper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "omdrop-radio"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
omdrop-engine = { path = "../omdrop-engine" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
